### ISSUE TITLE
Request Throttling

### ISSUE THREAD

**Issue by karthikb351** [aneesh-neelam/VITacademics#21]
Limit the number of requests from a particular user. 
Ideally, instead of saying it's too frequent, it's better to serve a cached version of the data with a timestamp saying how old the data is.
This works better since the client apps will always receive data on a request.

Maybe use an in-process memcache for this?

**Comment by aneesh-neelam** [comment]
OK first and foremost, a few clarifications regarding Heroku and Node.js

Heroku calls its instances dynos. We have 750 dyno hours per month for free. And it doesn't scale dynos automatically no matter what, for any language/platform. We'll be runnning only 1 dyno for the entire VITacademics Node.js Backend and Webapp at all times. One Heroku free dyno gives us single core of a 1.7 GHz Intel Xeon processor and 512 MB RAM. This is one of the very reasons why Heroku is used by so many startups. 

Now that gives us 31.25 dyno days per month. In a 31 day month, we get 6 hours to run a second dyno for cron jobs or for something else. And we get full uptime due to the first dyno always running. 

Now, Node.js uses a single threaded asynchronous non-blocking I/O model. Which means that while the Node.js app waits for VIT's server(s) to respond, it can squeeze in another client's request, or do something else in the time it spends waiting for I/O. I/O can be filesystem, database, network etc. In the time it takes to fetch the webpages from VIT, the app can parse some other user's captcha. That's the idea. We already know it can scale for atleast around a thousand simultaneous HTTP requests by stress testing and also by the successful execution of [GraVITas Premier League](https://github.com/IEEECS-VIT/GPL). I know there are claims about a million simultaneous request, but I'll not go that far. Besides, VIT's servers are slow, it'll have enough time to serve requests :-P 

But VIT's servers cannot handle as much, funnily enough. So instead of limiting the API calls to the Backend, let's limit the calls to VIT from the backend. There are no limits to MongoLab except that MongoDB itself has a hard limit on the number of simultaneous database connection pools it can create, which is more than 5000. You're supposed to reuse the same connection pool rather than create one every time. We know that again due to [GraVITas Premier League](https://github.com/IEEECS-VIT/GPL). 

I have an idea on how this can be done. First, I'll make some assumptions: 
- The client calls /data/refresh whenever user hits refresh and only if "Session Timed Out", it'll call login/auto

As @karthikb351 suggested, we can serve cached data. VIT's session is for 3 minutes, let's limit the number of refreshes from VIT to **1 per valid session**. 

So, suggestions: 
- Use only captchaless login at all times, **for everything** 
- We give our users the best experience possible, **so no manual captcha whatsoever**
- Call /data/first for first time use
- Call /data/refresh whenever the user hits refresh
- You get cached data **if the user has already refreshed during the same 3 minute session**
- You'll get Session Timed Out, in which case call /login/auto and then call /data/refresh
- Now it'll refresh data from VIT's server(s)
- This should be enough to prevent one user from abusing the crap out of VIT's server(s)
- Anything that is strictly confined to the Node.js backend or MongoDB, like token regeneration or timetable share, **call those as many times as you want, Node.js and MongoLab can easily handle it**

Backend TODO: 
- Serve saved data from MongoDB (faster than VIT anyway) if /data/refresh is called more than once per session. Can hold a boolean flag along with the cookie in [node-cache](https://github.com/ptarjan/node-cache)

**Comment by karthikb351** [comment]
I think we should go with giving the best experience possible. The idea is to completely eliminate the "Session timed out" message. Why does the client have to call `/auto` and then `/refresh` if it's timed out?

Can't `/refresh` log in again by itself?

That's what we should try and achieve. We won't reach any CPU limits anyway, so it won't cost us anything.

**Comment by aneesh-neelam** [comment]
The problem with combining `/data` and `/login` endpoints is that it'll take longer time to respond. 
Heroku times out if an endpoint takes longer than 30 seconds to respond. 

Now, combining both would mean that the request will take the combined time taken by the numerous HTTP requests made to VIT server(s). Remember, we are making two requests on `/login/auto` and making three requests on `/data/first` and `/data/refresh`. 

Throttling /data/refresh should be enough to stop people from incessantly calling VIT's server(s) whenever they hit refresh repeatedly.

**Comment by aneesh-neelam** [comment]
This is almost done. Will push in an hour.

**Comment by aneesh-neelam** [comment]
I've implemented what I've suggested in the above comment in ec37d20fb12e29106daee93b47c267afec464f6e

There are Refreshed (date) and Cached (boolean) keys in the JSON now. 

I'm closing the issue now, reopen it if we still have issues with VIT's server(s) being slow.
